version: "3.8"
services:
  api:
    build: . # = docker build .
    #image: loctran1991/fastapi:apiprod_v1
    depends_on:
      - postgres
    ports:
      - 5000:5000
    #volumes:
    #  - ./:/user/src/app:ro #sync when we have changed source code to container app folder
    #command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload #overrid cmd in Dockerfile when we have changed code
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: