apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-nginx
spec:
  acme:
    # The ACME server URL for production
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: loc.tran.niit@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-nginx-privatekey
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
          #class: nginx