"""add phone number to user table

Revision ID: 23954135b58d
Revises: e121e69cd877
Create Date: 2023-07-28 13:45:08.538410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23954135b58d'
down_revision = 'e121e69cd877'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True)) # pylint: disable=no-member
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number') # pylint: disable=no-member
    # ### end Alembic commands ###
