name: Build to K8s DigitalOcean
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repository
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 1e863feb-df3e-44bd-a1b2-643f5b4ec881


      - name: Check and update DNS record for services
        env:
          ip_loadbalancer: ""
        run: |
          "$ip_loadbalancer=$(kubectl -n nginx-ingress get svc nginx-ingress --output jsonpath='{.status.loadBalancer.ingress[*].ip}')"
          doctl compute domain records create luketran.xyz --record-type A --record-name fastapi --record-data $ip_loadbalancer



      

